---
- name: install nginx software
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    nginx

- include: debian-install.yml
  when: ansible_os_family == 'Debian'

- include: centos-install.yml
  when: (ansible_os_family == 'RedHat' and ansible_distribution == 'CentOS')

- name: add nginx main configuration
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_server_conf_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: add default virtual host nginx configuration
  template:
    src: global.j2
    dest: "{{ nginx_default_vhost_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: enable vhost nginx configuration
  file:
    src: "{{ nginx_default_vhost_filename }}"
    dest: "{{ nginx_sites_enabled_path }}/default"
    state: link
  when: "ansible_os_family == 'Debian'"
  notify: nginx reload


- name: set up default index page
  copy:
    src: index.html
    dest: "{{ nginx_document_root }}"
    owner: root
    group: root
    mode: 0644
#  notify: restart nginx
